CREATE DATABASE agencia CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE admin (
id_admin BIGINT(20)UNSIGNED AUTO_INCREMENT NOT NULL ,
nome VARCHAR(200) NOT NULL ,
login VARCHAR(200) NOT NULL ,
senha VARCHAR(200) NOT NULL ,
email VARCHAR(200) NOT NULL ,
PRIMARY KEY (id_user) ) ENGINE = InnoDB;

CREATE TABLE imagens (
id_imagem BIGINT(20) UNSIGNED AUTO_INCREMENT NOT NULL ,
src VARCHAR(200) NOT NULL ,
descricao VARCHAR(200) NOT NULL ,
PRIMARY KEY (id_imagem) ) ENGINE = InnoDB;
 
CREATE TABLE mensagem (
id_mensagem BIGINT(20) UNSIGNED AUTO_INCREMENT NOT NULL ,
nome VARCHAR(200) NOT NULL ,
email VARCHAR(200) NOT NULL ,
texto VARCHAR(1000) NOT NULL ,
PRIMARY KEY (id_mensagem) ) ENGINE = InnoDB;id

CREATE TABLE servicos (
id_servico BIGINT(20) UNSIGNED AUTO_INCREMENT NOT NULL ,
titulo_serviço VARCHAR(200) NOT NULL ,
descrição_servico VARCHAR(200) NOT NULL ,
icon_serviço VARCHAR(50) NOT NULL ,
PRIMARY KEY (id_servico) ) ENGINE = InnoDB;

CREATE TABLE curriculo (
id_item BIGINT(20) UNSIGNED AUTO_INCREMENT NOT NULL ,
titulo_item VARCHAR(200) NOT NULL ,
atributo VARCHAR(200) NOT NULL ,
conteudo VARCHAR(1000) NOT NULL ,
PRIMARY KEY (id_curriculo) ) ENGINE = InnoDB;


